// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using green_haven_store.Data;

#nullable disable

namespace green_haven_store.Migrations
{
    [DbContext(typeof(AllDBContext))]
    partial class AllDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("green_haven_store.Models.Cart", b =>
                {
                    b.Property<int>("Cart_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Cart_Id"));

                    b.Property<DateTime>("Cart_Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Cart_Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("Cart_Updated_At")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<bool?>("isOrderAdded")
                        .HasColumnType("bit");

                    b.HasKey("Cart_Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("green_haven_store.Models.Category", b =>
                {
                    b.Property<int>("Cat_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Cat_Id"));

                    b.Property<DateTime>("Cat_Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Cat_IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("Cat_IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Cat_Name")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Cat_Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Cat_Id = 1,
                            Cat_Date = new DateTime(2024, 11, 16, 18, 49, 33, 853, DateTimeKind.Local).AddTicks(8834),
                            Cat_IsActive = true,
                            Cat_IsDelete = false,
                            Cat_Name = "Plant"
                        });
                });

            modelBuilder.Entity("green_haven_store.Models.Order", b =>
                {
                    b.Property<int>("Order_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Order_Id"));

                    b.Property<int?>("CartIds")
                        .HasColumnType("int");

                    b.Property<DateTime>("Order_Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Order_IsPaymentDone")
                        .HasColumnType("bit");

                    b.Property<double>("Order_PayableAmount")
                        .HasColumnType("float");

                    b.Property<int?>("Order_Quantity")
                        .HasColumnType("int");

                    b.Property<double>("Order_Tax")
                        .HasColumnType("float");

                    b.Property<int?>("ProductIds")
                        .HasColumnType("int");

                    b.Property<int?>("ProductP_Id")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Order_Id");

                    b.HasIndex("ProductP_Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("green_haven_store.Models.Product", b =>
                {
                    b.Property<int>("P_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("P_Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("P_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("P_Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("P_IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("P_IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("P_Name")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("P_PictureUri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Price")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("P_Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            P_Id = 1,
                            CategoryId = 1,
                            P_Date = new DateTime(2024, 11, 16, 18, 49, 33, 853, DateTimeKind.Local).AddTicks(8994),
                            P_Description = "Have you ever wanted to grow your own adorable pineapple indoors? With the Bromeliad Pineapple, you can! This bromeliad sprouts a fun ornamental pineapple from a whorl of long green leaves. Sure to spark a conversation with your next dinner guests, you’ll know your pineapple fruit has reached maturity when it turns fragrant and a brighter shade of yellow. Although this variety is not grown for edible consumption, it’s still a unique gift or addition to any personal collection.",
                            P_IsActive = true,
                            P_IsDelete = false,
                            P_Name = "Bromeliad Pineapple",
                            P_PictureUri = "https://bloomscape.com/wp-content/uploads/2020/08/bloomscape_bromeliad-pineapple_charcoal-e1625250094764.jpg?ver=279190",
                            P_Price = "79.99"
                        },
                        new
                        {
                            P_Id = 2,
                            CategoryId = 1,
                            P_Date = new DateTime(2024, 11, 16, 18, 49, 33, 853, DateTimeKind.Local).AddTicks(8998),
                            P_Description = "Easy and graceful, with lush dark green fronds",
                            P_IsActive = true,
                            P_IsDelete = false,
                            P_Name = "Parlor Palm",
                            P_PictureUri = "https://bloomscape.com/wp-content/uploads/2020/08/bloomscape_parlor-palmloomscape_slate-e1625249746437.jpg?ver=279264",
                            P_Price = "69.99"
                        },
                        new
                        {
                            P_Id = 3,
                            CategoryId = 1,
                            P_Date = new DateTime(2024, 11, 16, 18, 49, 33, 853, DateTimeKind.Local).AddTicks(9000),
                            P_Description = "The Monstera deliciosa, also known as the Swiss Cheese Plant, is a striking tropical plant originating from the rainforests of southern Mexico. Lively and wild with large, tropical leaves make it a popular choice for indoor gardens.",
                            P_IsActive = true,
                            P_IsDelete = false,
                            P_Name = "Monstera Deliciosa",
                            P_PictureUri = "https://bloomscape.com/wp-content/uploads/2020/08/bloomscape_monstera_alt_clay.jpg?ver=279414",
                            P_Price = "84.99"
                        },
                        new
                        {
                            P_Id = 4,
                            CategoryId = 1,
                            P_Date = new DateTime(2024, 11, 16, 18, 49, 33, 853, DateTimeKind.Local).AddTicks(9002),
                            P_Description = "Impressive and tropical with large, glossy leaves that naturally split over time.",
                            P_IsActive = true,
                            P_IsDelete = false,
                            P_Name = "Bird of Paradise",
                            P_PictureUri = "https://bloomscape.com/wp-content/uploads/2020/08/bloomscape_bird-of-paradise_indigo.jpg?ver=279491",
                            P_Price = "139.99"
                        },
                        new
                        {
                            P_Id = 5,
                            CategoryId = 1,
                            P_Date = new DateTime(2024, 11, 16, 18, 49, 33, 853, DateTimeKind.Local).AddTicks(9004),
                            P_Description = "With dense foliage and lush fronds, the Bamboo Palm makes a statement. An air-purifying plant adaptable to low light, this palm can reach heights of up to 8 feet tall in the right conditions.\r\n\r\n",
                            P_IsActive = true,
                            P_IsDelete = false,
                            P_Name = "Bamboo Palm",
                            P_PictureUri = "https://bloomscape.com/wp-content/uploads/2020/08/bloomscape_bamboo-palm_stone.jpg?ver=279484",
                            P_Price = "160.99"
                        },
                        new
                        {
                            P_Id = 6,
                            CategoryId = 1,
                            P_Date = new DateTime(2024, 11, 16, 18, 49, 33, 853, DateTimeKind.Local).AddTicks(9006),
                            P_Description = "Popular for its use in Feng Shui, the Money Tree is a pet-friendly and air-purifying plant with large star-shaped leaves and a braided trunk to give your home a tropical feel.\r\n\r\n",
                            P_IsActive = true,
                            P_IsDelete = false,
                            P_Name = "Money Tree",
                            P_PictureUri = "https://bloomscape.com/wp-content/uploads/2020/08/bloomscape_money-tree_slate-e1643402075928.jpg?ver=279409",
                            P_Price = "135.99"
                        },
                        new
                        {
                            P_Id = 7,
                            CategoryId = 1,
                            P_Date = new DateTime(2024, 11, 16, 18, 49, 33, 853, DateTimeKind.Local).AddTicks(9008),
                            P_Description = "Architectural and sturdy, this plant is easy to care for and highly adaptable. Also known as a Snake Plant and Mother-in-Law’s Tongue.\r\n\r\n",
                            P_IsActive = true,
                            P_IsDelete = false,
                            P_Name = "Sansevieria",
                            P_PictureUri = "https://bloomscape.com/wp-content/uploads/2020/08/bloomscape_sansevieria_charcoal-e1633460982733.jpg?ver=279439",
                            P_Price = "119.99"
                        },
                        new
                        {
                            P_Id = 8,
                            CategoryId = 1,
                            P_Date = new DateTime(2024, 11, 16, 18, 49, 33, 853, DateTimeKind.Local).AddTicks(9010),
                            P_Description = "Easy and graceful, with lush dark green fronds",
                            P_IsActive = true,
                            P_IsDelete = false,
                            P_Name = "Parlor Palm",
                            P_PictureUri = "https://bloomscape.com/wp-content/uploads/2020/08/bloomscape_parlor-palmloomscape_slate-e1625249746437.jpg?ver=279264",
                            P_Price = "69.99"
                        },
                        new
                        {
                            P_Id = 9,
                            CategoryId = 1,
                            P_Date = new DateTime(2024, 11, 16, 18, 49, 33, 853, DateTimeKind.Local).AddTicks(9012),
                            P_Description = "Robust and dramatic, the Burgundy Rubber Tree sports large, glossy leaves on durable, upright stems. This striking plant is ready to make a statement in your home with its dark, moody color palette ranging from deep forest green to rich burgundy red. This low-maintenance plant will be happiest in a spot with bright indirect light.\r\n\r\n",
                            P_IsActive = true,
                            P_IsDelete = false,
                            P_Name = "Burgundy Rubber Tree",
                            P_PictureUri = "https://bloomscape.com/wp-content/uploads/2022/08/bloomscape_burgundy-rubber-tree_lg_charcoal.jpg?ver=927090",
                            P_Price = "84.99"
                        },
                        new
                        {
                            P_Id = 10,
                            CategoryId = 1,
                            P_Date = new DateTime(2024, 11, 16, 18, 49, 33, 853, DateTimeKind.Local).AddTicks(9014),
                            P_Description = "Easy and graceful, with lush dark green fronds",
                            P_IsActive = true,
                            P_IsDelete = false,
                            P_Name = "Parlor Palm",
                            P_PictureUri = "https://bloomscape.com/wp-content/uploads/2020/08/bloomscape_parlor-palmloomscape_slate-e1625249746437.jpg?ver=279264",
                            P_Price = "69.99"
                        },
                        new
                        {
                            P_Id = 11,
                            CategoryId = 1,
                            P_Date = new DateTime(2024, 11, 16, 18, 49, 33, 853, DateTimeKind.Local).AddTicks(9016),
                            P_Description = "With graceful layered leaves, the hardy ZZ Plant is a statement plant that can reach up to 2.5 feet tall. This drought-tolerant plant is tough, beautiful, and nearly indestructible.\r\n\r\n",
                            P_IsActive = true,
                            P_IsDelete = false,
                            P_Name = "ZZ Plant",
                            P_PictureUri = "https://bloomscape.com/wp-content/uploads/2020/08/bloomscape_zz-plant_charcoal-e1625251444532.jpg?ver=279472",
                            P_Price = "119.99"
                        },
                        new
                        {
                            P_Id = 12,
                            CategoryId = 1,
                            P_Date = new DateTime(2024, 11, 16, 18, 49, 33, 853, DateTimeKind.Local).AddTicks(9018),
                            P_Description = "A colorful and low-maintenance air plant, the Bromeliad Summer is a striking houseplant that adds warmth to your home. With a bright and cheery magenta flower, this bromeliad is pet-friendly and makes for a great gift for any plant lover or beginner plant parent.",
                            P_IsActive = true,
                            P_IsDelete = false,
                            P_Name = "Bromeliad Summer",
                            P_PictureUri = "https://bloomscape.com/wp-content/uploads/2023/04/BloomScape_SM_Bromeliad-Summer_white-scaled.jpg?ver=1022056",
                            P_Price = "49.99"
                        },
                        new
                        {
                            P_Id = 13,
                            CategoryId = 1,
                            P_Date = new DateTime(2024, 11, 16, 18, 49, 33, 853, DateTimeKind.Local).AddTicks(9020),
                            P_Description = "Easy-going Monstera with striking, fenestrated leaves. Also known as the Swiss Cheese Vine.\r\n\r\n",
                            P_IsActive = true,
                            P_IsDelete = false,
                            P_Name = "Monstera Adansonii",
                            P_PictureUri = "https://bloomscape.com/wp-content/uploads/2019/11/bloomscape_monstera-adansonii_md_clay-scaled-e1721151440768.jpg?ver=440338",
                            P_Price = "79.99"
                        },
                        new
                        {
                            P_Id = 14,
                            CategoryId = 1,
                            P_Date = new DateTime(2024, 11, 16, 18, 49, 33, 853, DateTimeKind.Local).AddTicks(9022),
                            P_Description = "The Ficus Tineke (Ficus elastica), the vibrant younger sibling of our popular Burgundy Rubber Tree. Boasting variegated leaves in hues of creamy pink, yellow, and green, this rubber tree is a captivating presence in any interior setting, whether it graces your space solo or thrives amidst your collection.\r\n\r\n",
                            P_IsActive = true,
                            P_IsDelete = false,
                            P_Name = "Ficus Tineke",
                            P_PictureUri = "https://bloomscape.com/wp-content/uploads/2023/08/230805_BB_fiscus_elastica_tineke_slate-scaled-e1692911022828.jpg?ver=1057588",
                            P_Price = "79.99"
                        },
                        new
                        {
                            P_Id = 15,
                            CategoryId = 1,
                            P_Date = new DateTime(2024, 11, 16, 18, 49, 33, 853, DateTimeKind.Local).AddTicks(9024),
                            P_Description = "Vibrant and bright with patterned, neon green leaves.",
                            P_IsActive = true,
                            P_IsDelete = false,
                            P_Name = "Neon Prayer Plant",
                            P_PictureUri = "https://bloomscape.com/wp-content/uploads/2020/09/bloomscape_neon-prayer-plant_charcoal-e1625250223838.jpg?ver=292318",
                            P_Price = "69.99"
                        });
                });

            modelBuilder.Entity("green_haven_store.Models.User", b =>
                {
                    b.Property<int>("U_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("U_Id"));

                    b.Property<string>("U_Address")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("U_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("U_Email")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("U_IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("U_IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("U_Name")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("U_Password")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("U_Pincode")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("U_Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("U_Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            U_Id = 1,
                            U_Address = "65 Foresthead Street, Kitchener",
                            U_Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            U_Email = "test@gmail.com",
                            U_IsActive = true,
                            U_IsDelete = false,
                            U_Name = "Test Customer",
                            U_Password = "test",
                            U_Pincode = "N2L 3T6",
                            U_Type = "user"
                        },
                        new
                        {
                            U_Id = 2,
                            U_Address = "Canada",
                            U_Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            U_Email = "admin@gmail.com",
                            U_IsActive = true,
                            U_IsDelete = false,
                            U_Name = "Admin",
                            U_Password = "admin",
                            U_Pincode = "N2L 3T6",
                            U_Type = "admin"
                        });
                });

            modelBuilder.Entity("green_haven_store.Models.Cart", b =>
                {
                    b.HasOne("green_haven_store.Models.Product", "Product")
                        .WithMany("Carts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("green_haven_store.Models.User", "User")
                        .WithMany("Carts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("green_haven_store.Models.Order", b =>
                {
                    b.HasOne("green_haven_store.Models.Product", null)
                        .WithMany("Orders")
                        .HasForeignKey("ProductP_Id");

                    b.HasOne("green_haven_store.Models.User", null)
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("green_haven_store.Models.Product", b =>
                {
                    b.HasOne("green_haven_store.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("green_haven_store.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("green_haven_store.Models.Product", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("green_haven_store.Models.User", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
